# Generated by Django 3.0.8 on 2020-09-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='picture',
            field=models.ImageField(null=True, upload_to='community_pictures/'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='picture',
            field=models.ImageField(null=True, upload_to='feature_pictures/'),
        ),
    ]
