# Generated by Django 3.0.8 on 2020-09-07 12:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplestore',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
