# Generated by Django 3.0.8 on 2020-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200714_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('BAR', 'Bar'), ('RES', 'Restaurant'), ('CLB', 'Club'), ('REI', 'Religious institution'), ('OFF', 'Office'), ('SMT', 'Supermarket'), ('CNA', 'Cinema'), ('HOS', 'Hospital'), ('HTL', 'Hotel'), ('RSE', 'Retail store'), ('EST', 'Estate'), ('PRS', 'Professional services'), ('ECO', 'eCommerce'), ('SCH', 'School'), ('ENT', 'Entertainment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='feature',
            name='community_type',
            field=models.CharField(choices=[('BAR', 'Bar'), ('RES', 'Restaurant'), ('CLB', 'Club'), ('REI', 'Religious institution'), ('OFF', 'Office'), ('SMT', 'Supermarket'), ('CNA', 'Cinema'), ('HOS', 'Hospital'), ('HTL', 'Hotel'), ('RSE', 'Retail store'), ('EST', 'Estate'), ('PRS', 'Professional services'), ('ECO', 'eCommerce'), ('SCH', 'School'), ('ENT', 'Entertainment')], max_length=32),
        ),
    ]
