# Generated by Django 3.0.8 on 2020-08-05 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200731_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['id'], 'verbose_name_plural': 'communities'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='community',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='communities_admined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='community',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='communities_using', to='core.Feature'),
        ),
        migrations.AlterField(
            model_name='community',
            name='key',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='communities_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
