# Generated by Django 3.0.8 on 2020-08-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200805_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='db_host',
        ),
        migrations.RemoveField(
            model_name='database',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='database',
            name='db_pass',
        ),
        migrations.RemoveField(
            model_name='database',
            name='db_port',
        ),
        migrations.AddField(
            model_name='database',
            name='key',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='value',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
