# Generated by Django 3.0.8 on 2020-08-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200814_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='access',
            field=models.CharField(choices=[('PUBL', 'Public'), ('USER', 'User')], default='PUBL', max_length=32),
            preserve_default=False,
        ),
    ]
