# Generated by Django 3.0.8 on 2020-08-15 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_database_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('access', models.CharField(choices=[('PUBL', 'Public'), ('USER', 'User')], max_length=32)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_store', to='core.Community')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_store', to='core.Feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MapStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('access', models.CharField(choices=[('PUBL', 'Public'), ('USER', 'User')], max_length=32)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_store', to='core.Community')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_store', to='core.Feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('string_value', models.TextField()),
                ('access', models.CharField(choices=[('PUBL', 'Public'), ('USER', 'User')], max_length=32)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_store', to='core.Community')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_store', to='core.Feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
