# Generated by Django 3.0.8 on 2020-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200815_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplestore',
            old_name='string_value',
            new_name='value',
        ),
        migrations.AddField(
            model_name='feature',
            name='key',
            field=models.CharField(default='ffffffff', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
