# Generated by Django 3.0.8 on 2020-08-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200816_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
