# Generated by Django 3.0.8 on 2020-08-19 22:14

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200816_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='simplestore',
            name='access',
            field=models.CharField(choices=[('PUBL', 'Public'), ('USER', 'User'), ('ADMN', 'Admin')], max_length=32),
        ),
        migrations.AlterField(
            model_name='simplestore',
            name='value',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
