# Generated by Django 3.0.8 on 2020-08-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200819_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplestore',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
