# Generated by Django 3.0.8 on 2020-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='picture',
            field=models.ImageField(upload_to='community_pictures/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
