# Generated by Django 3.0.8 on 2020-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feature_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='picture',
            field=models.ImageField(upload_to='feature_pictures/'),
        ),
    ]
