# Generated by Django 3.0.8 on 2020-09-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200901_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='approved',
            field=models.NullBooleanField(),
        ),
    ]
