# Generated by Django 3.0.8 on 2020-09-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_feature_community_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(blank=True, choices=[('BAR', 'Bar'), ('RES', 'Restaurant'), ('CLB', 'Club'), ('REI', 'Religious institution'), ('OFF', 'Office'), ('SMT', 'Supermarket'), ('CNA', 'Cinema'), ('HOS', 'Hospital'), ('HTL', 'Hotel'), ('RSE', 'Retail store'), ('EST', 'Estate'), ('PRS', 'Professional services'), ('ECO', 'eCommerce'), ('SCH', 'School'), ('ENT', 'Entertainment')], max_length=32, null=True),
        ),
    ]
