# Generated by Django 3.0.8 on 2020-09-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200901_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='communities_with_type', to='core.CommunityType'),
        ),
        migrations.AlterField(
            model_name='communitytype',
            name='value',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
